spring:
  main:
    allow-circular-references: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_OAUTH_ID}
            clientSecret: ${GOOGLE_OAUTH_PW}
            scope:
              - email
              - profile
          kakao:
            client-id: ${KAKAO_OAUTH_ID}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao # 도메인 변경
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_emil
            client-name: Kakao
        provider:
              kakao:
                authorization_uri: https://kauth.kakao.com/oauth/authorize
                token_uri: https://kauth.kakao.com/oauth/tokne
                user-info-uri: https://kapi.kakao.com/v2/user/me
                user_name_attribute: id
domain: 15.164.185.150