spring:
  main:
    allow-circular-references: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_OAUTH_ID}
            clientSecret: ${GOOGLE_OAUTH_PW}
            scope:
              - email
              - profile